RETOcontrolPanel/Models/newsViewModel.cs
namespace RETOcontrolPanel.Models
{
    using Entities;
    using Microsoft.AspNet.Identity;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web.Mvc;

    public partial class NewsViewModel
    {
       
        
        [Key]
        public int News_Id { get; set; }

        [Required]
        [StringLength(150)]
        [Display(Name = "TITLE")]
        public string Title { get; set; }

        //    [Required]
        //[StringLength(200)]
     //  public  string content { get; set; }

      //  public DateTime Time_Created { get; set; }

        [StringLength(250)]
        [Display(Name = "Image Path")]
        public string ImgURL { get; set; }

     //   [StringLength(10)]
        //public string CreatedBy { get; set; }

        //public DateTime CreatedDate { get; set; }

        //[StringLength(10)]
        //public string ModifiedBy { get; set; }

        //[StringLength(10)]
        //public string ModifiedDate { get; set; }

        public bool IsActive { get; set; }

        [Display(Name = "Show Image?")]
        public bool? ShowImage { get; set; }

        [UIHint("tinymce_jquery_full"), AllowHtml]
        [Display(Name = "Content")]
        public string Body { get; set; }

        public NewsViewModel(News news)
        {
            this.News_Id = news.News_Id;
            this.Title = news.Title;
        //    this.Body = news.content;
            this.ImgURL = news.ImgURL;
            // all other fields go here
            
        }
        public NewsViewModel() {
        }

        public News ConvertToEntity() {
            string userid = System.Web.HttpContext.Current.User.Identity.GetUserId();
            News news = new News
            {
                News_Id = this.News_Id,
                Title = this.Title,
               // News_body = this.News_body,
               // content = this.Body,
                Time_Created = System.DateTime.Now,
                ImgURL = this.ImgURL,
                CreatedBy = String.IsNullOrEmpty(userid) ? "0" : userid,
                CreatedDate = System.DateTime.Now,
                ModifiedBy = String.IsNullOrEmpty(userid) ? "0" : userid,
                ModifiedDate = System.DateTime.Now.ToShortDateString().Substring(0,10),
                IsActive = this.IsActive,
                ShowImage = this.ShowImage
            };

            return news;
        }
    }

}

RETOcontrolPanel/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Entities;
using RETOcontrolPanel.Models;

namespace RETOcontrolPanel.Controllers
{
    public class NewsController : Controller
    {
        private Model1 db = new Model1();
        NewsViewModel img = new NewsViewModel();

        // GET: News
        public ActionResult Index()
        {
            var news = db.News.Where(n => n.IsActive == true).Include(n => n.News_body).ToList();
            return View(news.Select(x => new IndexModel(x)).ToList());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
           // var obj = db.News.Where(u => u.ImgURL == img.ImgURL).FirstOrDefault();
           //newsView.News_body.body = HttpUtility.HtmlDecode(newsView.News_body.body);
            if (id == null)
            {

               
                //newsView.ImgURL = obj.ImgURL;
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Include("News_body").SingleOrDefault(x => x.News_Id == id);
            if (news == null)
            {
                return HttpNotFound();
            }
            news.News_body.body = HttpUtility.HtmlDecode(news.News_body.body);
            return View(news);
        }

        // GET: News/Create
        public ActionResult Create()
        {
            ViewBag.News_Id = new SelectList(db.News_body, "News_Id", "body");
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "News_Id,Title,content,Body,ImgURL")] RETOcontrolPanel.Models.NewsViewModel news)
        
{
            try
            { 
                string fileName = "";
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];
                    if (file != null && file.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                        file.SaveAs(path);
                    }
                }
                if (ModelState.IsValid)
                {
                    
                    news.ShowImage = true;
                    //news.Time_Created = System.DateTime.Now;
                    news.ImgURL = fileName;
                    //news.CreatedBy = "System";
                    //news.CreatedDate = System.DateTime.Today;
                    news.IsActive = true;

                    string content = news.Body.Replace("<br/>", Environment.NewLine);

                    content = Regex.Replace(content, "<.*?>", string.Empty);
                    

                    News entity = news.ConvertToEntity();

                    entity.content = content.Substring(0, content.Length > 200 ? 200 : content.Length);

                    db.News.Add(entity);

                    db.News_body.Add(new News_body()
                    {
                       body = HttpUtility.HtmlEncode(news.Body),
                        News_Id = entity.News_Id
                    });

                    db.SaveChanges();

                }

                ViewBag.News_Id = new SelectList(db.News_body, "News_Id", "body", news.News_Id);
                
               // return View(news);
                return RedirectToAction("Index");
            }
            catch (Exception ex) {
                ViewBag.Message = "upload does not save to folder";
                return View();
            }
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            ViewBag.News_Id = new SelectList(db.News_body, "News_Id", "body", news.News_Id);
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "News_Id,Title,content,Time_Created,ImgURL,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate,IsActive,ShowImage")] News news)
        {
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.News_Id = new SelectList(db.News_body, "News_Id", "body", news.News_Id);
            return View(news);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }

            news.News_body.body = HttpUtility.HtmlDecode(news.News_body.body);
            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);
           // db.News.Remove(news);
            news.IsActive = false;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RETOcontrolPanel/Views/News/Create.cshtml
@model RETOcontrolPanel.Models.NewsViewModel

@{
    ViewBag.Title = "Create";

}

<h2>Create</h2>


@using (Html.BeginForm("Create", "News", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>News</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger " })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.News_body, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.News_body, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.News_body, "", new { @class = "text-danger " })
        </div>
    </div>*@

    <div class="form-group">
        @*@Html.LabelFor(model => model.ImgURL, htmlAttributes: new { @class = "control-label col-md-2" })Upload Image*@

        <div class="col-md-10 col-md-offset-2">
            <input type="file" name="btnUpload" value="save to file" class="control-label form-control " />
            @*@Html.EditorFor(model => model.ImgURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImgURL, "", new { @class = "text-danger" })*@

            @* here is the error  *@

            @*@Html.TextBox(model => model.ImgURL,  new { type = "file", @class = "form-control" }) <br />
                @Html.ValidationMessageFor(model => model.ImgURL, "", new { @class = "text-danger" })*@


        </div>
    </div>

    @*

        <div class="form-group">
            @Html.LabelFor(model => model.Time_Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time_Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time_Created, "", new { @class = "text-danger" })
            </div>
        </div>


            <div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
                </div>
            </div>

                   <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

    *@


    @*<div class="form-group">
            @Html.LabelFor(model => model.ShowImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ShowImage)
                    @Html.ValidationMessageFor(model => model.ShowImage, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RETOcontrolPanel/Views/News/Delete.cshtml
@model Entities.News

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>News</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.News_body.body)
        </dt>

        <dd>
            @Html.Raw(Model.News_body.body)
        </dd>



        @*<dt>
            @Html.DisplayNameFor(model => model.content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.content)
        </dd>*@

        <dd>
            @*@Html.DisplayFor(model => model.ImgURL)*@

            <img style="width:800px;height:380px;" src="@Url.Content("~/images/"+Model.ImgURL)" />

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time_Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time_Created)
        </dd>




        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShowImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowImage)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RETOcontrolPanel/Views/News/Details.cshtml
@model Entities.News

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>News</h4>
    <hr />
    <dl class="dl-horizontal">

        @*<dt>
            <h4>@Html.DisplayNameFor(model => model.Title)</h4>
        </dt>*@
        <dd>
            <h4><b>@Html.DisplayFor(model => model.Title)</b></h4>
        </dd>

        @*<dt>
            <h4>@Html.DisplayNameFor(model => model.News_body.body) </h4>
        </dt>*@
        <dd>
            @Html.Raw(Model.News_body.body)
        </dd>




        @*<dt>
            @Html.DisplayNameFor(model => model.content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.content)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.Time_Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time_Created)
        </dd>*@

        <dd>
            @*@Html.DisplayFor(model => model.ImgURL)*@

            <img style="width:800px;height:380px;" src="@Url.Content("~/images/"+Model.ImgURL)"/>
            
        </dd>

        @*

            <dt>
            @Html.DisplayNameFor(model => model.ImgURL)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShowImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowImage)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.News_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RETOcontrolPanel/Views/News/Edit.cshtml
@model Entities.News

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>News</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.News_Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.content, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.content, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Time_Created, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Time_Created, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Time_Created, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.ImgURL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ImgURL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImgURL, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
        </div>
    </div>
    @*
        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShowImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ShowImage)
                    @Html.ValidationMessageFor(model => model.ShowImage, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RETOcontrolPanel/Views/News/Index.cshtml
@model IEnumerable<RETOcontrolPanel.Models.IndexModel>
    

@{
    ViewBag.Title = "Index";
}

<h2>NEWS</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table>
@foreach (var item in Model)
{
    <tr>
        <td>
            <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
        </td>
    </tr>
    <tr>
        <td>

            @Html.DisplayFor(modelItem => item.content)@*.ToString().Substring(0 , item.content.Length > 100 ? 150 : item.content.Length)*@
            @Html.ActionLink("Read more", "Details", new { id = item.News_Id })
        </td>
    </tr>
    
    @*<tr>
        <td>
            @Html.DisplayFor(modelItem => item.ImgURL)
        </td>
    </tr>*@

    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.News_Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.News_Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.News_Id })
        </td>
    </tr>
}

</table>